/**
 * Input for scripts/build-timeline.ts: scene anchors and cue phrases for
 * video 03, taken from script.md ("Starts at" and every "On ..." cue).
 * Phrases are written exactly as they appear in voiceover.txt. Extra beat
 * cues (fewMonths, tiny, decides...) break holds longer than ~4 s.
 */
import type { TimelineSpec } from "../../lib/timeline-spec";

export const TIMELINE_SPEC: TimelineSpec = {
  fps: 30,
  sceneLeadFrames: 6,
  logo: {
    id: "s02-logo",
    afterPhrase: "Why not print enough to make everyone rich",
    breathingRoomSec: 0.4,
    durationSec: 3.0,
    resumeLeadSec: 0.3,
  },
  endCard: {
    id: "end-card",
    afterPhrase: "See you there",
    gapSec: 0.6,
    durationSec: 20,
  },
  scenes: [
    {
      id: "s01-hook",
      anchor: "This is a real banknote",
      cues: {
        hundredTrillion: "One hundred trillion dollars",
        issued: "It was issued in Zimbabwe",
        january: "in January",
        cameOut: "On the day it came out",
        fewMonths: "A few months earlier",
        doubling: "doubling roughly every",
        canPrint: "So if a government can print money",
        whyNot: "why doesn't every country just print",
        everyoneRich: "make everyone rich",
      },
    },
    {
      id: "s03-island",
      anchor: "To answer that, let's shrink the economy",
      cues: {
        tiny: "something tiny",
        imagine: "Imagine an island",
        loaves: "There are ten loaves of bread",
        tenDollars: "and ten dollars",
        oneDollar: "So each loaf costs one dollar",
        decides: "government decides everyone should be richer",
        prints: "prints ten more dollars",
        twiceMoney: "Everyone has twice as much money",
        onlyTen: "still only ten loaves",
        bakers: "Bakers notice",
        towardTwo: "the price of a loaf moves toward two dollars",
        nobodyRicher: "Nobody got richer",
        doubled: "The money doubled",
        halfAsMuch: "each dollar now buys half as much",
        simplest: "That's inflation at its simplest",
        chasing: "more money chasing the same amount of stuff",
      },
    },
    {
      id: "s04-wealth",
      anchor: "Money isn't wealth",
      cues: {
        breadIs: "Bread is wealth",
        houses: "Houses, phones",
        claim: "Money is just a claim",
        printingClaims: "Printing more claims",
        moreBread: "doesn't create more bread",
      },
    },
    {
      id: "s05-zimbabwe",
      anchor: "In Zimbabwe, the government printed",
      cues: {
        payBills: "printed more and more money to pay its bills",
        lessAndLess: "producing less and less",
        moreFewer: "More money, fewer goods",
        peak: "At the peak",
        seventyNine: "seventy-nine billion percent a month",
        thinkAbout: "Think about what that means",
        paidMorning: "If you got paid in the morning",
        evening: "by the evening",
        saving: "Saving was pointless",
        spend: "spend your money the moment you got it",
        faster: "pushed prices up even faster",
        april: "And in April",
        stopped: "stopped using its own currency",
        switched: "People switched to US dollars",
      },
    },
    {
      id: "s06-us",
      anchor: "But wait. The United States printed",
      cues: {
        feb2020: "In February twenty twenty",
        twoYears: "Two years later",
        twentyTwo: "almost twenty-two trillion",
        forty: "about forty percent",
        whyNot: "So why didn't America become Zimbabwe",
        inflationCame: "Inflation did come",
        june2022: "In June twenty twenty-two",
        biggestJump: "the biggest jump",
        hurt: "That hurt",
        notHyper: "it wasn't hyperinflation",
      },
    },
    {
      id: "s07-reasons",
      anchor: "There are four big reasons",
      cues: {
        timing: "First, timing",
        shutDown: "the economy was shut down",
        savingInstead: "saving instead of spending",
        satStill: "A lot of that new money sat still",
        wholeWorld: "the whole world wants dollars",
        fiftySeven: "About fifty-seven percent",
        heldByBanks: "held by central banks",
        printACurrency: "When you print a currency the whole world uses",
        spreads: "the extra money spreads much further",
        ownCurrency: "the US borrows in its own currency",
        manyCountries: "Many countries borrow in dollars",
        cantPrintDollars: "they can't print dollars",
        debtsBigger: "their debts get bigger",
        trust: "And fourth, trust",
        independentFed: "is independent from the government",
        raisedRates: "raised interest rates hard",
        believed: "People believed it would",
      },
    },
    {
      id: "s08-brake",
      anchor: "Remember the last video",
      cues: {
        createdByBanks: "Most money is created by banks",
        higherRates: "higher rates slow that down",
        // "brake" is heard as "break": the words just before it.
        brake: "That's the",
        alwaysBad: "So is printing money always bad",
        littleInflation: "aim for a little inflation",
        twoPercent: "around two percent a year",
        slowly: "A slowly growing money supply",
        danger: "The danger isn't printing",
        faster: "much faster than the economy can grow",
      },
    },
    {
      id: "s09-who",
      anchor: "So who decides how much money to print",
      cues: {
        notPresident: "not the president or the parliament",
        independent: "It's an independent central bank",
        onPurpose: "That's on purpose",
        election: "an election, a war, a crisis",
        separated: "were separated from them",
        oneVote: "isn't one vote away",
        breaks: "When that separation breaks",
        stories: "stories like Zimbabwe",
      },
    },
    {
      id: "s10-takeaway",
      anchor: "So, why can't countries just print as much as they want",
      cues: {
        worth: "Because money only works if it's worth something",
        buysLess: "every dollar buys less",
        trusting: "stop trusting it at all",
        printMoney: "You can print money",
        printBread: "You can't print bread",
        education: "This is education",
        newSeries: "we start a new series",
        // "sportsbooks" is heard as "sports books": the words just before it.
        sportsbooks: "we begin with",
        youDo: "You do",
        seeYou: "See you there",
      },
    },
  ],
};
