/**
 * Input for scripts/build-timeline.ts: scene anchors and cue phrases for
 * video 02, taken from script.md ("Starts at" and every "On ..." cue).
 * Phrases are written exactly as they appear in voiceover.txt.
 */
import type { TimelineSpec } from "../../lib/timeline-spec";

export const TIMELINE_SPEC: TimelineSpec = {
  fps: 30,
  sceneLeadFrames: 6,
  logo: {
    id: "s02-logo",
    afterPhrase: "most of the money in the world exists only like that",
    breathingRoomSec: 0.4,
    durationSec: 3.0,
    resumeLeadSec: 0.3,
  },
  endCard: {
    id: "end-card",
    afterPhrase: "See you there",
    gapSec: 0.6,
    durationSec: 20,
  },
  scenes: [
    {
      id: "s01-hook",
      anchor: "Open your banking app",
      cues: {
        balance: "four thousand, two hundred and eighty dollars",
        whereIs: "Now, where is that money",
        notInVault: "Not in a vault",
        // Added to break the 8.5s hold before "It's a promise" (brand: nothing static over ~4s).
        nameOnIt: "with your name on it",
        stranger: "The truth is stranger",
        holding: "isn't money the bank is holding for you",
        promise: "It's a promise",
        mostMoney: "most of the money in the world",
      },
    },
    {
      id: "s03-textbook",
      anchor: "Here's the story most of us were taught",
      cues: {
        deposit: "You deposit one thousand dollars",
        vault: "keeps a little in the vault",
        lends: "lends the rest",
        savingsLoan: "Your savings become their loan",
        anotherBank: "lands in another bank",
        multiplier: "the money multiplier",
      },
    },
    {
      id: "s04-twist",
      anchor: "It makes sense",
      cues: {
        notHow: "it's not how it works",
        boe2014: "In twenty fourteen",
        published: "published a paper",
        quote: "rather than banks lending out deposits",
        actOfLending: "the act of lending creates deposits",
        plainWords: "In plain words",
        newMoney: "it creates new money",
      },
    },
    {
      id: "s05-watch",
      anchor: "Let's watch it happen",
      cues: {
        sarahWalks: "Sarah walks into a bank",
        carLoan: "twenty thousand dollar car loan",
        approves: "The bank approves it",
        notTake: "does not take twenty thousand dollars from anyone's account",
        twoEntries: "It makes two entries",
        sarahOwes: "Sarah owes the bank",
        accountShows: "Sarah's account now shows",
        didntExist: "that money didn't exist",
        nobodyPrinted: "Nobody printed it",
        typed: "The bank typed it",
      },
    },
    {
      id: "s06-two-layers",
      anchor: "Sarah buys the car",
      cues: {
        toDealer: "The money moves to the dealer's account",
        doesntVanish: "It doesn't vanish",
        differentBank: "a different bank",
        sendReal: "send real money",
        secondKind: "a second kind of money",
        reserves: "called reserves",
        neverTouch: "You and I never touch it",
        twoLayers: "So there are two layers",
        centralCreates: "The central bank creates cash and reserves",
        commercialBanks: "commercial banks create the money you actually use",
      },
    },
    {
      id: "s07-destroyed",
      anchor: "And here's the other half",
      cues: {
        paysBack: "When Sarah pays the loan back",
        destroys: "repaying loans destroys money",
        notFixed: "So money isn't a fixed pile",
        createdEvery: "It's created every time someone borrows",
        everyMortgage: "Every mortgage and every car loan adds money",
        everyRepayment: "Every repayment takes some away",
      },
    },
    {
      id: "s08-cash",
      anchor: "How much of the money around us is actually cash",
      cues: {
        unitedStates: "In the United States",
        broadMoney: "the broad money supply",
        cash: "two and a half trillion",
        nineInTen: "nine out of every ten dollars",
        uk: "In the UK",
        ninetySeven: "ninety-seven percent",
      },
    },
    {
      id: "s09-iou",
      anchor: "So what is your balance, really",
      cues: {
        iou: "It's an IOU",
        whenDeposit: "When you deposit money",
        books: "On the bank's books",
        owes: "They're something it owes",
        keepAside: "how much does a US bank legally have to keep aside",
        sinceMarch: "Since March twenty twenty",
        zeroPercent: "zero percent",
      },
    },
    {
      id: "s10-infinite",
      anchor: "So if banks can create money by typing",
      cues: {
        infinite: "why don't they create infinite amounts",
        threeThings: "Three things stop them",
        makesSense: "a loan only makes sense",
        borrowers: "real borrowers",
        capital: "hold capital",
        rates: "sets interest rates",
        lastOne: "That last one matters most",
        ratesUp: "When rates go up",
        fightInflation: "to fight inflation",
      },
    },
    {
      id: "s11-trust",
      anchor: "So most of the time, the promise holds",
      cues: {
        fallApart: "things fall apart fast",
        depression: "During the Great Depression",
        march9: "On March ninth, twenty twenty-three",
        svbCustomers: "customers of Silicon Valley Bank",
        fortyTwo: "forty-two billion dollars",
        quarter: "a quarter of all its deposits",
        hundredBillion: "one hundred billion dollars",
        shutDown: "It was shut down that same day",
        onHand: "didn't have that much on hand",
        bonds: "tied up in bonds",
        notEveryone: "if not everyone asks at once",
      },
    },
    {
      id: "s12-insurance",
      anchor: "That's why deposit insurance exists",
      cues: {
        twoFifty: "two hundred and fifty thousand dollars",
        since1933: "nineteen thirty-three",
        atSvb: "At Silicon Valley Bank",
        ninetyFour: "over ninety-four percent",
        notInsured: "they weren't insured at all",
        coveredEveryone: "covered everyone",
      },
    },
    {
      id: "s13-takeaway",
      anchor: "So, does the money in your bank account exist",
      cues: {
        notCash: "Not as cash",
        notVault: "Not as a pile in a vault",
        promise: "It exists as a promise",
        rules: "backed by rules",
        insurance: "by insurance",
        trust: "by the trust of millions",
        notPanic: "That's not a reason to panic",
        education: "This is education, not financial advice",
        ifBanks: "if banks can create money",
        printWhy: "why can't countries just print",
        nextVideo: "That's the next video",
        seeYou: "See you there",
      },
    },
  ],
};
