/**
 * Refreshes the copies in gpt/ from their sources, so GPT (Codex) reads the
 * same rules and Remotion notes as Claude. Run after editing CLAUDE.md or the
 * skills:  node gpt/sync.mjs   (or npm run gpt:sync)
 *
 *   CLAUDE.md                  -> gpt/AGENTS.md
 *   .claude/skills/<name>/     -> gpt/skills/<name>/   (the Remotion notes GPT needs)
 */
import { cpSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const gpt = path.join(root, "gpt");

const SKILLS = [
  "remotion-best-practices",
  "remotion-markup",
  "remotion-render",
  "remotion-captions",
  "remotion-interactivity",
  "remotion-studio",
];

const header = `<!--
  Generated by gpt/sync.mjs from CLAUDE.md. Do not edit here: edit CLAUDE.md, then run \`npm run gpt:sync\`.
  For GPT: wherever this file says "Claude" or ".claude/skills/", read "you" and "gpt/skills/".
-->

`;
const rules = readFileSync(path.join(root, "CLAUDE.md"), "utf8").replaceAll(".claude/skills/", "gpt/skills/");
writeFileSync(path.join(gpt, "AGENTS.md"), header + rules);

rmSync(path.join(gpt, "skills"), { recursive: true, force: true });
for (const name of SKILLS) {
  const from = path.join(root, ".claude", "skills", name);
  if (!existsSync(from)) throw new Error(`Missing skill folder: ${from}`);
  cpSync(from, path.join(gpt, "skills", name), { recursive: true });
}

console.log(`gpt/AGENTS.md and ${SKILLS.length} skill folders refreshed.`);
