/**
 * Sound-effect cue sheet for Video 01. Every event is placed from the same cue
 * frames (timeline.json) and timing helpers the scenes animate with, so a sound
 * always lands on its motion. scripts/build-sfx-track.ts mixes this list into
 * one aligned track that Video01 plays under the voiceover.
 *
 * Sounds (public/sfx, made by scripts/make-sfx.ts):
 *   tick   counters and small steps     pop    labels and numbers appearing
 *   tap    cards, blocks, bars landing   thump  big numbers landing
 *   whoosh scene changes, big moves      swish  small moves, strike-throughs
 *   chime  the key insight of a scene    riser  build-up before a reveal
 */
import { DURATION, VIDEO } from "../../brand/tokens";
import { LOGO_INTRO_TIMING } from "../../components/LogoIntro";
import { DATA } from "./data";
import { JAGGED_TROUGHS } from "./parts/jaggedCurve";
import { MARKET_TROUGHS } from "./parts/marketPath";
import { s01MonthAt } from "./scenes/S01Hook";
import { S04_SEGMENT_DONE } from "./scenes/S04Mattress";
import { s05YearAt } from "./scenes/S05Compounding";
import { s07CounterAt } from "./scenes/S07Curve";
import { s09YearAt } from "./scenes/S09TippingPoint";
import { getScene, sceneTiming, TIMELINE, TRANSITION_FRAMES, type SceneId } from "./timeline";

export const SFX_SOUNDS = ["tick", "pop", "tap", "thump", "whoosh", "swish", "chime", "riser"] as const;
export type SfxSound = (typeof SFX_SOUNDS)[number];

export type SfxEvent = {
  readonly sound: SfxSound;
  /** Absolute frame where the sound starts. */
  readonly frame: number;
  /** Linear gain (each sound file peaks at -3 dBFS). */
  readonly volume: number;
  /** Playback rate: 1 = as made, 1.12 = about two semitones higher. */
  readonly rate?: number;
};

/** The mixed track, relative to public/. Generated by `npm run sfx`. */
export const SFX_TRACK_FILE = "audio/100-a-month-40-years/sfx-track.wav";
/** Gain for the whole sfx track in Video01 (one knob to balance it against the voice). */
export const SFX_TRACK_VOLUME = 1.4;

/** Default level per sound: well under the voice, so the channel stays calm. */
const LEVEL: Record<SfxSound, number> = {
  tick: 0.1,
  pop: 0.2,
  tap: 0.26,
  thump: 0.42,
  whoosh: 0.16,
  swish: 0.14,
  chime: 0.13,
  riser: 0.2,
};

/** Frames from a whoosh's start to its loudest point. */
const WHOOSH_PEAK = Math.round(0.35 * VIDEO.fps);
/** Length of the riser, so it can end exactly on a reveal. */
const RISER_FRAMES = Math.round(1.6 * VIDEO.fps);

const events: SfxEvent[] = [];

/** Adds sounds for one scene; `at` takes frames relative to the scene start. */
const scene = (id: SceneId) => {
  const start = getScene(id).startFrame;
  const T = sceneTiming(id);
  const add = (sound: SfxSound, frame: number, gain = 1, rate = 1) =>
    events.push({ sound, frame: Math.round(start + frame), volume: LEVEL[sound] * gain, rate });
  /**
   * A tick each time a counter's shown value changes, at most one every
   * `minGap` frames, with the pitch rising across the run.
   */
  const ticks = (
    valueAt: (frame: number) => number,
    from: number,
    to: number,
    { minGap = 2, gain = 1, rateFrom = 1, rateTo = 1.3 } = {},
  ) => {
    let last = valueAt(from - 1);
    let lastTick = -Infinity;
    for (let f = from; f <= to; f++) {
      const v = valueAt(f);
      if (v !== last && f - lastTick >= minGap) {
        add("tick", f, gain, rateFrom + (rateTo - rateFrom) * ((f - from) / Math.max(1, to - from)));
        lastTick = f;
      }
      last = v;
    }
  };
  return { T, add, ticks, cue: T.cue };
};

/** Soft whoosh peaking in the middle of each cross-fade. */
for (const s of TIMELINE.scenes.slice(1)) {
  const quickCut = s.id === "s06-why-7";
  events.push(
    quickCut
      ? { sound: "swish", frame: s.startFrame - 2, volume: LEVEL.swish * 1.2 }
      : { sound: "whoosh", frame: s.startFrame + Math.round(TRANSITION_FRAMES / 2) - WHOOSH_PEAK, volume: LEVEL.whoosh },
  );
}

// S01: "$" waits, "100" lands, months tick by, "?" rises, the guess, then $262,481 slams in.
{
  const { add, ticks, cue } = scene("s01-hook");
  add("tick", cue("hundredAppears"), 0.8);
  add("pop", cue("hundredSpoken"));
  add("pop", cue("hundredSpoken") + 4, 0.6, 1.12);
  ticks(s01MonthAt, cue("everyMonth"), cue("howMuch"), { minGap: 2, gain: 0.9 });
  add("swish", cue("howMuch"));
  add("pop", cue("howMuch") + 4, 1.1, 0.9);
  add("pop", cue("guessFifty"), 0.9);
  add("swish", cue("realAnswer"), 0.6);
  add("thump", cue("fiveTimes"));
  add("chime", cue("fiveTimes") + 2);
  add("swish", cue("fiveTimes") + 6, 0.7);
}

// S02: four slices land, the amber slice pulls out, the name appears.
{
  const { add } = scene("s02-logo");
  const L = LOGO_INTRO_TIMING;
  const fps = VIDEO.fps;
  for (let i = 0; i < 4; i++) {
    // A slice is visually in place about 40% into its ease-out.
    add("tap", (L.sliceStart + i * L.sliceStagger + L.sliceDuration * 0.4) * fps, 0.9, 1 + i * 0.06);
  }
  add("swish", L.pullStart * fps, 1.3);
  add("chime", (L.pullStart + L.pullDuration * 0.6) * fps, 1.4);
  add("pop", L.revealStart * fps, 0.8);
}

// S03: slots, three cards, "$3 a day", three strike-throughs.
{
  const { T, add, cue } = scene("s03-rules");
  for (let i = 0; i < 3; i++) add("tick", T.anchor + i * 4, 0.7, 1 + i * 0.1);
  add("tap", cue("card1"));
  add("pop", cue("perDay"), 0.8);
  add("tap", cue("card2"), 1, 1.06);
  for (const at of [cue("noRaises"), cue("noBonuses"), cue("noLuckyPicks")]) {
    add("pop", at, 0.7);
    add("swish", at + 8, 0.9);
  }
  add("tap", cue("card3"), 1, 1.12);
  add("chime", cue("card3") + 2, 0.8);
  add("whoosh", T.duration - 8, 0.7);
}

// S04: the bar outline, 40 yearly segments ticking up, "$48,000", then it slides to the baseline chip.
{
  const { add, cue } = scene("s04-mattress");
  add("tap", cue("barAppears"), 0.8);
  S04_SEGMENT_DONE.forEach((done, i) => add("tick", done - 4, 0.8, 1 + (i / S04_SEGMENT_DONE.length) * 0.35));
  add("thump", cue("fortyEight"), 0.8);
  add("pop", cue("fortyEight"), 0.8);
  add("whoosh", cue("keepInMind") + 10, 1.1);
}

// S05: blocks and caps land, the growth loop, then the row rushes to year 40.
{
  const { add, ticks, cue } = scene("s05-compounding");
  add("pop", cue("sevenLabel"));
  add("tap", cue("yearOne"));
  add("pop", cue("aboutForty"), 0.9, 1.12);
  add("tap", cue("yearTwo"), 1, 1.06);
  add("pop", cue("lastYearsGrowth"), 0.8);
  add("swish", cue("lastYearsGrowth") + 12, 0.9);
  add("pop", cue("growthEarnsGrowth"), 1, 1.2);
  add("chime", cue("growthEarnsGrowth") + 4, 0.8);
  add("whoosh", cue("slowAtFirst"), 0.9);
  ticks(s05YearAt, cue("slowAtFirst") + 6, cue("slowAtFirst") + 6 + 7 * 5, { minGap: 3, rateTo: 1.1 });
  add("whoosh", cue("thenItDoesnt"), 1.1);
  ticks(s05YearAt, cue("thenItDoesnt") + 4, cue("thenItDoesnt") + 4 + (DATA.series.length - 11), {
    minGap: 1,
    gain: 0.8,
    rateFrom: 1.1,
    rateTo: 1.5,
  });
  add("tap", cue("thenItDoesnt") + 4 + (DATA.series.length - 11) + 4, 1.1, 1.12);
}

// S06: a century of market draws in, ~10% then ~7%, the pill, the drops flash.
{
  const { add, cue } = scene("s06-why-7");
  add("whoosh", cue("lastHundredYears"), 0.8);
  add("pop", cue("tenPercent"));
  add("pop", cue("afterInflation"), 1.1, 1.12);
  add("chime", cue("afterInflation") + 2, 0.8);
  add("pop", cue("todaysDollars"), 0.7);
  MARKET_TROUGHS.forEach((_, i) => add("thump", cue("marketDropped") + i * 6, 0.6, 0.9));
}

// S07: three lines draw, milestones at 10, 20, 30, a build-up, then the final count to $262,481.
{
  const { add, ticks, cue } = scene("s07-curve");
  add("swish", cue("mattressLine"), 1.1);
  add("swish", cue("fourPercent"), 1.1, 1.08);
  add("whoosh", cue("sevenPercent"), 0.9);
  add("pop", cue("tenYears"));
  add("pop", cue("onlyFiveMore"), 0.7);
  add("swish", cue("quitHere"), 0.9);
  add("pop", cue("twentyYears"), 1, 1.06);
  add("pop", cue("thirtyYears"), 1, 1.12);
  add("riser", cue("fortyYears") - RISER_FRAMES);
  add("whoosh", cue("fortyYears"), 0.9);
  ticks((f) => Math.floor(s07CounterAt(f) / 2000), cue("fortyYears"), cue("finalNumberEnd"), {
    minGap: 2,
    rateFrom: 1,
    rateTo: 1.4,
  });
  add("thump", cue("finalNumberEnd"));
  add("chime", cue("finalNumberEnd") + 1, 1.2);
}

// S08: four decade bars grow (each taller, each a little higher), then stack.
{
  const { add, cue } = scene("s08-decades");
  const bars = [cue("bar1"), cue("bar2"), cue("bar3"), cue("bar4")];
  bars.forEach((at, i) => {
    add("tap", at, 0.9 + i * 0.1, 1 + i * 0.08);
    add("pop", at + 8, 0.7, 1 + i * 0.08);
  });
  const stack = cue("stack");
  [20, 10, 0].forEach((delay, k) => {
    add("swish", stack + delay + 12, 0.8, 1 + k * 0.05);
    add("tap", stack + delay + 34, 0.7, 1 + k * 0.06);
  });
  add("pop", stack + 40, 0.9);
  add("chime", cue("onlyTime"), 0.9);
}

// S09: years tick to 11, freeze on the tipping point, then rush to 40.
{
  const { add, ticks, cue } = scene("s09-tipping-point");
  const year = (f: number) => Math.round(s09YearAt(f));
  ticks(year, 12, cue("yearEleven"), { minGap: 2, rateTo: 1.2 });
  add("thump", cue("yearEleven"), 0.9);
  add("chime", cue("yearEleven") + 2, 1.2);
  add("pop", cue("moreThan"), 0.9, 1.12);
  add("whoosh", cue("fromThatPoint"));
  ticks(year, cue("fromThatPoint"), cue("fromThatPoint") + 90, { minGap: 2, gain: 0.8, rateFrom: 1.2, rateTo: 1.5 });
  add("pop", cue("gapWider"));
}

// S10: same deposit, same rate, a late start, the gap, the catch-up card.
{
  const { add, cue } = scene("s10-cost-of-waiting");
  add("pop", cue("sameHundred"), 0.8);
  add("pop", cue("sameSeven"), 0.8, 1.08);
  add("whoosh", cue("startAt35"), 0.8);
  add("pop", cue("threeQuarters"), 0.7);
  add("swish", cue("youDont"));
  add("thump", cue("endUpWith122"), 0.7);
  add("pop", cue("endUpWith122"), 0.8);
  add("swish", cue("lessThanHalf"));
  add("pop", cue("lessThanHalf") + 10, 0.8);
  add("whoosh", cue("catchUp"));
  add("tap", cue("catchUp") + 10);
  add("pop", cue("twoFifteen"));
  add("thump", cue("moreThanDouble"), 0.7);
  add("pop", cue("moreThanDouble"), 0.9, 1.12);
  add("chime", cue("bestDecade"));
}

// S11: the full circle, the $48K slice separates, 82% pulls out, the circle becomes the logo.
{
  const { add, cue } = scene("s11-where-it-came-from");
  add("tap", cue("fullCircle"));
  add("pop", cue("howMuchPutIn"), 0.7);
  add("swish", cue("fortyEight"));
  add("swish", cue("otherTwoFourteen"), 1, 1.1);
  add("thump", cue("eightyTwo"), 0.9);
  add("chime", cue("eightyTwo") + 2, 1.2);
  add("pop", cue("lessThanFifth"), 0.8);
  add("whoosh", cue("sumOfParts"), 1.1);
  add("tap", cue("sumOfParts") + 40, 0.9, 1.12);
  add("pop", cue("sumOfParts") + 45 + 10, 0.9);
}

// S12: the smooth line, it turns jagged, crashes, recoveries, then fees.
{
  const { add, cue } = scene("s12-fine-print");
  add("swish", cue("smoothLine"));
  add("pop", cue("longTermAverage"), 0.8);
  add("swish", cue("notSmooth"), 1.2, 0.85);
  JAGGED_TROUGHS.forEach((_, i) => add("thump", cue("theyCrash") + i * 8, 0.55, 0.9 - i * 0.05));
  JAGGED_TROUGHS.forEach((_, i) => add("pop", cue("keptInvesting") + i * 10, 0.7, 1 + i * 0.08));
  add("whoosh", cue("fees"));
  add("tap", cue("fees") + 10);
  add("pop", cue("cutResult"), 0.8);
  add("thump", cue("tensOfThousands"), 0.7);
  add("pop", cue("tensOfThousands"), 0.8);
  add("pop", cue("notAdvice"), 0.6);
}

// S13: three recap lines, the total, two strike-throughs, then "time".
{
  const { add, cue } = scene("s13-takeaway");
  [cue("line1"), cue("line2"), cue("line3")].forEach((at, i) => add("pop", at, 0.8, 1 + i * 0.06));
  add("swish", cue("quarterMillion"));
  add("thump", cue("quarterMillion") + 12, 0.8);
  add("pop", cue("quarterMillion") + 12, 0.9, 1.12);
  for (const at of [cue("notBecause"), cue("perfectInvestment")]) {
    add("pop", at, 0.6);
    add("swish", at + 8, 0.9);
  }
  add("whoosh", cue("becauseOfTime"), 0.9);
  add("thump", cue("becauseOfTime") + 4, 0.7);
  add("chime", cue("becauseOfTime") + 5, 1.3);
  add("pop", cue("amount"), 0.7);
  add("pop", cue("startDate"), 1, 1.12);
  add("pop", cue("ifYouWant") + 8, 0.7);
}

// End card: logo, prompt, then the two video slots (timing as in components/EndCard.tsx).
{
  const { add } = scene("end-card");
  const fps = VIDEO.fps;
  add("tap", 0, 0.9);
  add("pop", 0.15 * fps, 0.7);
  for (let i = 0; i < 2; i++) add("swish", (0.4 + i * DURATION.stagger * 2) * fps, 0.8, 1 + i * 0.08);
  add("chime", 0.6 * fps, 1);
}

export const SFX_EVENTS: readonly SfxEvent[] = events.sort((a, b) => a.frame - b.frame);
